Changing the namespace to RonasIT/AutoDoc solving #62
RonasIT/laravel-swagger pull request #135
Opened 2024-09-23 08:36 UTC by ahmedashraf093

# Description

Changing the package namespace from `RonasIT\Support\AutoDoc` to `RonasIT\AutoDoc`

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ y] My code follows the style guidelines of this project
- [ y] I have performed a self-review of my own code
- [ y] I have commented my code, particularly in hard-to-understand areas
- [ y] I have made corresponding changes to the documentation
- [ y] My changes generate no new warnings
- [ y] Any dependent changes have been merged and published in downstream modules

2024-10-08 05:02 UTC, DenTray requested changes

2024-10-08 05:02 UTC, DenTray commented
@ahmedashraf093 please resolve conflicts

2024-10-08 09:30 UTC, ahmedashraf093 commented
> @ahmedashraf093 please resolve conflicts

done

2024-10-10 11:28 UTC, DenTray approved these changes

2024-10-10 11:28 UTC, DenTray commented on tests/fixtures/SwaggerServiceTest/tmp_data_post_user_request_with_object_params.json
> +
```suggestion
```

2024-10-10 11:29 UTC, DenTray approved these changes

2024-10-10 11:29 UTC, merged