feat: set up project to use Paratest
RonasIT/laravel-swagger pull request #136
Opened 2024-09-30 05:15 UTC by vitgrams

Done:

- Save production doc only after all workers completed their job;
- Added lock for tmp documentation file (for read & write as well).

2024-09-30 05:18 UTC, vitgrams commented
@DenTray Could you please review this one?

2024-10-14 08:46 UTC, DenTray requested changes

2024-10-14 08:46 UTC, DenTray commented on src/Drivers/BaseDriver.php
> +        return json_decode($content, true);
let's move all low-level code to the separate function

```php
$content = $this->getFileContentWithLock($this->tempFilePath);

return json_decode($content, true);
```

2024-10-14 08:46 UTC, DenTray commented on src/Drivers/BaseDriver.php
> +        $handle = @fopen($this->tempFilePath, 'r');
let's use try catch instead

2024-11-29 09:14 UTC, vitgrams commented
@DenTray Could you please take a look at this again?

2024-12-03 09:12 UTC, DenTray requested changes

2024-12-03 16:56 UTC, vitgrams commented
@DenTray Done. Could you please take a look?

2024-12-10 14:18 UTC, DenTray requested changes

2025-03-31 05:10 UTC, DenTray requested changes

2025-03-31 05:10 UTC, DenTray commented on src/Drivers/BaseDriver.php
> +    public function saveSharedTmpData(callable $callback): void
```suggestion
    public function appendProcessDataToTmpFile(callable $callback): void
```

2025-04-04 09:31 UTC, DenTray requested changes

2025-04-04 09:31 UTC, DenTray commented on src/Support/Mutex.php
> +    protected function readJsonFromStream($handle): ?array
please order methods by the visibility criteria:
- public
- protected
- private

2025-04-04 09:31 UTC, DenTray commented on src/Support/Mutex.php
> +        $fileResource = fopen($filePath, $fileReadWriteMode);
```suggestion
        $fileResource = fopen($filePath, self::MODE_FILE_READ_WRITE);
```

2025-04-08 14:28 UTC, DenTray requested changes

2025-04-08 14:28 UTC, DenTray commented on src/Support/Mutex.php
> +    protected function writeJsonToStream($handle, array $data): void
let's remove method and call this logic directly

2025-04-08 14:28 UTC, DenTray commented on src/Support/Mutex.php
> +        fwrite($handle, json_encode($data));
let's simplify this mutex by only read and write content, let's move json_encode of it

2025-04-08 14:28 UTC, DenTray commented on src/Support/Mutex.php
> +        return ($content === false) ? null : json_decode($content, true);
let's remove json_decode out of the mutex class

2025-04-08 14:28 UTC, DenTray commented on src/Support/Mutex.php
> +        return ($content === false) ? null : json_decode($content, true);
let's use `(string) stream_get_contents($handle)` directly without method wrapping

2025-04-08 14:28 UTC, DenTray commented on src/Support/Mutex.php
> +    ): void {
could we use typehint for the handle?

```suggestion
    protected function acquireLock($handle, int $operation): void
    {
```

2025-04-09 06:56 UTC, NikitaYakovlev commented on src/Support/Mutex.php
> +    ): void {
As of PHP 8.0, there is no official type hint called resource in the same sense as built-in scalar types like int, string, or float. PHP recognizes resource as a keyword, but when used as a type hint, it will be treated as a class name rather than a specific type.

2025-04-09 07:17 UTC, NikitaYakovlev commented on src/Drivers/BaseDriver.php
>      }
This method is used to remove temporary files of processes after merging data into the main file.
![image](https://github.com/user-attachments/assets/1c85c043-23b6-4373-b699-ffa05c2aeec2)

2025-04-11 06:46 UTC, DenTray requested changes

2025-04-11 06:46 UTC, DenTray commented on config/auto-doc.php
> +            /*
```suggestion

            /*
```

2025-04-11 06:55 UTC, DenTray approved these changes

2025-04-11 06:55 UTC, DenTray commented on src/Drivers/BaseDriver.php
> +            return empty($data) ? null : json_decode($data, true);
```suggestion
            return (empty($data)) ? null : json_decode($data, true);
```

2025-04-11 06:55 UTC, DenTray commented on src/Drivers/BaseDriver.php
>      }
@NikitaYakovlev got it! thanks!

2025-04-11 07:04 UTC, DenTray commented on src/Support/Mutex.php
> +            return ($content === false) ? null : $content;
could we do it like this?

```suggestion
            return (string) stream_get_contents($handle);
```

2025-04-28 08:44 UTC, DenTray approved these changes

2025-04-28 08:44 UTC, DenTray commented on src/Drivers/BaseDriver.php
> +        $this->mutex->writeFileWithLock($this->tempFilePath, function ($sharedData) use ($appendDataCallback) {
```suggestion
        $this->mutex->writeFileWithLock($this->tempFilePath, function (string $tmpFileContent) use ($appendDataCallback) {
```

2025-04-28 08:44 UTC, DenTray commented on src/Contracts/SwaggerDriverContract.php
> +     * Save (result) temporary data
```suggestion
     * Add current process tmp data to the temp documentation file
```

2025-04-28 08:44 UTC, DenTray commented on src/Contracts/SwaggerDriverContract.php
> +     * @param callable $callback
```suggestion
     * @param callable $callback with 1 array argument, containing the current temp file content as array
```

2025-04-28 08:44 UTC, DenTray commented on src/Contracts/SwaggerDriverContract.php
> +     * Get (result) temporary data
```suggestion
     * Get temporary data from the temp file shared between all PHPUnit processes
```

2025-04-28 08:44 UTC, DenTray commented on src/Drivers/BaseDriver.php
> +            $resultDocContent = $appendDataCallback(json_decode($sharedData, true));
```suggestion
            $resultDocContent = $appendDataCallback(json_decode($tmpFileContent, true));
```

2025-04-28 08:44 UTC, DenTray commented on src/Drivers/BaseDriver.php
> +            return (empty($data)) ? null : json_decode($data, true);
```suggestion
            return json_decode($data, true);
```

2025-04-28 08:50 UTC, DenTray approved these changes

2025-04-28 08:50 UTC, DenTray commented on src/Drivers/BaseDriver.php
> +            $resultDocContent = $appendDataCallback(json_decode($tmpFileContent, true));
```suggestion
        $this->mutex->writeFileWithLock($this->tempFilePath, function (string $tempFileContent) use ($appendDataCallback) {
            $resultDocContent = $appendDataCallback(json_decode($tempFileContent, true));
```

2025-04-29 04:02 UTC, DenTray commented on src/Support/Mutex.php
> +
```suggestion
```

2025-04-29 04:26 UTC, DenTray requested changes

2025-04-29 04:26 UTC, DenTray commented on src/Support/Mutex.php
> +            fclose($handle);
```suggestion
        $fileResource = fopen($filePath, self::MODE_FILE_READ);

        try {
            $this->acquireLock($fileResource, LOCK_SH);

            return (string) stream_get_contents($fileResource);
        } finally {
            flock($fileResource, LOCK_UN);
            fclose($fileResource);
```

2025-04-29 04:26 UTC, DenTray commented on src/Support/Mutex.php
> +        while (!flock($handle, $operation)) {
```suggestion
    protected function acquireLock($fileResource, int $operation): void
    {
        $retryCounter = 0;

        $maxRetries = $this->maxRetries;
        $waitTime = $this->waitTime;

        while (!flock($fileResource, $operation)) {
```

2025-04-29 04:32 UTC, DenTray commented on src/Support/Mutex.php
> +            usleep($waitTime);
```suggestion
        while (!flock($fileResource, $operation)) {
            if ($retryCounter >= $this->maxRetries) {
                throw new RuntimeException('Unable to lock file');
            }

            usleep($this->waitTime);
```

2025-04-29 04:58 UTC, DenTray requested changes

2025-04-29 04:58 UTC, DenTray commented on tests/LocalDriverTest.php
> +        $tmpDocPath = __DIR__ . "/../storage/temp_documentation_{$token}.json";
```suggestion
        $processTempFilePath = __DIR__ . "/../storage/temp_documentation_{$token}.json";
```

2025-04-29 04:58 UTC, DenTray commented on tests/LocalDriverTest.php
>      public function testSaveTmpData()
```suggestion
    public function testAppendProcessTempDataToTempFile()
```

2025-04-29 05:00 UTC, DenTray commented on tests/RemoteDriverTest.php
>      public function testSaveTmpData()
```suggestion
    public function testSaveProcessTempData()
```

2025-04-29 05:08 UTC, DenTray commented on tests/StorageDriverTest.php
>      public function testSaveTmpData()
```suggestion
    public function testAppendProcessDataToTempFile()
```

2025-04-29 05:23 UTC, DenTray requested changes

2025-04-30 04:00 UTC, DenTray commented on tests/support/Traits/SwaggerServiceMockTrait.php
> +                $this->functionCall(name: 'saveProcessTmpData', arguments: [$savedProcessTmpData ?? $processTmpData]),
```suggestion
                $this->functionCall(
                    name: 'saveProcessTmpData',
                    arguments: [$savedProcessTmpData ?? $processTmpData],
                ),
```

2025-04-30 10:31 UTC, DenTray requested changes

2025-04-30 10:31 UTC, DenTray commented on tests/support/Traits/MockTrait.php
> +    /**
@RGO230 as discussed please use code from the package and remove it from here

2025-05-06 09:22 UTC, DenTray approved these changes

2025-05-06 09:30 UTC, DenTray commented on tests/support/Traits/SwaggerServiceMockTrait.php
> +                result: empty($processTmpData)
```suggestion
                result: (empty($processTmpData))
```

2025-05-06 09:31 UTC, DenTray commented on tests/support/Traits/SwaggerServiceMockTrait.php
> +            $this->functionCall(name: 'saveProcessTmpData', arguments: [$saveTmpData]),
```suggestion
            $this->functionCall('getProcessTmpData', $getTmpData),
            $this->functionCall('saveProcessTmpData', [$saveTmpData]),
```

2025-05-06 09:32 UTC, DenTray commented on tests/support/Traits/SwaggerServiceMockTrait.php
> +            $this->functionCall(name: 'getProcessTmpData', result: $tmpData),
```suggestion
            $this->functionCall('getProcessTmpData', $tmpData),
```

2025-05-06 09:33 UTC, DenTray commented on tests/support/Traits/SwaggerServiceMockTrait.php
> +            $this->functionCall(name: 'getDocumentation', result: $data),
```suggestion
            $this->functionCall('getDocumentation', $data),
```

2025-05-06 09:34 UTC, DenTray commented on tests/support/Traits/SwaggerServiceMockTrait.php
> +            $this->functionCall(name: 'saveData'),
```suggestion
            $this->functionCall('saveData'),
```

2025-05-06 09:34 UTC, DenTray approved these changes

2025-05-07 03:49 UTC, DenTray approved these changes

2025-05-07 03:50 UTC, merged