feat: create contribution guide
RonasIT/laravel-swagger pull request #60
Opened 2022-08-25 09:00 UTC by Goodmain

2022-08-25 09:18 UTC, astorozhevsky requested changes

2022-08-25 09:18 UTC, astorozhevsky commented on CONTRIBUTING.md
> +## Guidelines
I suggest adding a rule about `Commit Message Format` - https://www.conventionalcommits.org/en/v1.0.0/

2022-08-25 09:27 UTC, Goodmain commented on CONTRIBUTING.md
> +## Guidelines
@astorozhevsky Done

2022-08-26 05:06 UTC, astorozhevsky approved these changes

2022-08-26 06:37 UTC, merged