Evikulov/readme update
RonasIT/laravel-swagger pull request #63
Opened 2022-09-07 08:06 UTC by EVikulov

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-07 08:47 UTC, astorozhevsky requested changes

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
>  ### Example
please remove this heading

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
>  ## Usages
```suggestion
## Usage
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +To collect documentation run following steps:
```suggestion
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> + ```
```suggestion
 ```json
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> + ```
```suggestion
 ```

```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +2. Prepare test case code of API endpoint
```suggestion
2. Create test for testing API endpoint:
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +    public function testUpdate()
```suggestion
public function testUpdate()
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +    {
```suggestion
{
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +        $data = json_decode(file_get_contents('update_user.json'), true);
```suggestion
    $data = json_decode(file_get_contents('update_user.json'), true);
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +        $response = $this->json('put', '/users/1', $data);
```suggestion
    $response = $this->json('put', '/users/1', $data);
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +        $response->assertStatus(Response::HTTP_NO_CONTENT);
```suggestion
    $response->assertStatus(Response::HTTP_NO_CONTENT);
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +    }
```suggestion
}
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> + ```
```suggestion
 ```

```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +For correct working of plugin you have to dispose all the validation rules in the rules() method of `YourRequest` class,
```suggestion
For correct working of plugin you have to dispose all the validation rules in the `rules()` method of `UpdateUserDataRequest` class,
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +which must be connected to the controller via DependencyInjection. In annotation of custom request you can specify
```suggestion
which must be connected to the controller via Dependency Injection.
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +
let's add example of controller method:

```php
public function update(UpdateUserDataRequest $request)
{
     ...
}
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
>   - **@summary** - short description of request
need to add the sentence before:

```md
You can use the following annotations in your request classes to customize documentation of your API endpoints:
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> + - **@first_name** - Description of the field from the rules method
please revert

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +summary and description. Plugin will take validation rules from your request and use it as description
```suggestion
Plugin will take validation rules from your request and use it as description
```

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
>   If you do not create a class Request, the summary, Implementation Notes and parameters will be empty.
please remove the text below to the line `so, you can specify way to collect documentation by creating your custom data collector class.`

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +### Test result
please remove the heading

2022-09-07 08:47 UTC, astorozhevsky commented on readme.md
> +![img.png](assets/images/img.png)
add the steps before:

4. Run tests
5. Go to route defined in config `auto-doc.route`
6. Profit!

And paster the image here.

2022-09-08 07:35 UTC, DenTray commented on readme.md
> +1. Create request data fixture
let's remove the first point and use permanent data inside the test case

2022-09-08 07:36 UTC, DenTray commented on readme.md
> +3. Create request file code.
```suggestion
3. Create request class.
```

2022-09-08 07:38 UTC, DenTray commented on readme.md
> +For correct working of plugin you have to dispose all the validation rules
please place it under the class example

2022-09-08 07:45 UTC, DenTray commented on readme.md
> +## Usage
let's extend the structure

```php
## Usage

### Basic usage
...
### Annotations
...
### Configs
...

### Custom driver
```

2022-09-08 07:47 UTC, DenTray commented on readme.md
> +If you do not create a class Request, the summary, Implementation Notes and parameters will be empty.
let's mark this sentence as a note

2022-09-08 07:50 UTC, DenTray commented on readme.md
> +So, you can specify the way to collect documentation by creating your custom data collector class.
Please remove this sentece and describe the "Custom driver" block

2022-09-08 07:51 UTC, DenTray commented on readme.md
> +4. Create Controller file code
```suggestion
4. Inject the request class into controller method
```

2022-09-08 07:52 UTC, DenTray commented on readme.md
> +6. Go to route defined in config auto-doc.route
```suggestion
6. Go to route defined in the `auto-doc.route` config
```

2022-09-27 11:14 UTC, astorozhevsky approved these changes

2022-09-27 11:47 UTC, DenTray requested changes

2022-09-27 11:47 UTC, DenTray commented on readme.md
> +passing the tests.
```suggestion
passing PHPUnit tests.
```

2022-09-27 11:47 UTC, DenTray commented on readme.md
> +    > For older versions add the `AutoDocServiceProvider` to the
```suggestion
    > For elder versions add the `AutoDocServiceProvider` to the
```

2022-09-27 11:47 UTC, DenTray commented on readme.md
> + 2. Add middleware `\RonasIT\Support\AutoDoc\Http\Middleware\AutoDocMiddleware::class` into `Http/Kernel.php`.
```suggestion
 2. Add `\RonasIT\Support\AutoDoc\Http\Middleware\AutoDocMiddleware::class` middleware to the global HTTP middleware stack in `Http/Kernel.php`.
```

2022-09-27 11:47 UTC, DenTray commented on readme.md
> + 3. Add `\RonasIT\Support\AutoDoc\Tests\AutoDocTestCaseTrait` in your `TestCase` in `tests/TestCase.php`
```suggestion
 3. Add `\RonasIT\Support\AutoDoc\Tests\AutoDocTestCaseTrait` trait to `tests/TestCase.php`
```

2022-09-27 11:47 UTC, DenTray commented on readme.md
> +        */
```suggestion
    {
        /**
         * Determine if the user is authorized to make this request.
         *
         * @return bool
         */
```

2022-09-27 11:47 UTC, DenTray commented on readme.md
> +        */
```suggestion
        /**
         * Validation Rules
         *
         * @return array
         */
```

2022-09-27 11:47 UTC, DenTray commented on readme.md
> +    > must be connected to the controller via `dependency injection`.
```suggestion
    > must be connected to the controller via [dependency injection](https://laravel.com/docs/9.x/container#introduction).
```

2022-09-27 11:47 UTC, DenTray commented on readme.md
> +    > Plugin will take validation rules from your request and use it as description
```suggestion
    > Plugin will take validation rules from the request class and generate fields description
```

2022-09-27 11:47 UTC, DenTray commented on readme.md
> +You can specify way to collect documentation by creating your custom driver.
```suggestion
You can specify the way to collect documentation by creating your own custom driver.
```

2022-09-27 11:52 UTC, DenTray approved these changes

2022-09-27 11:53 UTC, merged