#67: Increase covering by unit tests
RonasIT/laravel-swagger pull request #75
Opened 2023-02-27 12:38 UTC by vitgrams

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-27 12:49 UTC, vitgrams commented
@DenTray Done. Could you please review this code?

2023-02-27 15:12 UTC, DenTray requested changes

2023-02-27 15:12 UTC, DenTray commented on tests/AutoDocMiddlewareTest.php
> +        $middleware  = new AutoDocMiddleware();
```suggestion
        $middleware = new AutoDocMiddleware();
```

2023-02-27 15:12 UTC, DenTray commented on tests/SwaggerServiceTest.php
> +        ], 'testRequestWithoutRuleType');
let's move it to the separate `generateGetRolesRequest`

2023-02-28 11:42 UTC, vitgrams commented
@DenTray All conversations have benn resolved. Could you please take another look at this?

2023-02-28 15:00 UTC, DenTray requested changes

2023-03-01 01:06 UTC, DenTray requested changes

2023-03-01 01:11 UTC, DenTray requested changes

2023-03-01 01:11 UTC, DenTray commented on tests/TestCase.php
> +    protected function generateResponse($fixture, int $status = 200, array  $headers = []): Response
```suggestion
    protected function generateResponse($fixture, int $status = 200, array $headers = []): Response
```

2023-03-01 01:11 UTC, DenTray commented on tests/TestCase.php
> +        return new Response(($fixture) ? $this->getFixture($fixture) : null, $status, $headers);
```suggestion

        return new Response(($fixture) ? $this->getFixture($fixture) : null, $status, $headers);
```

2023-03-01 01:12 UTC, DenTray approved these changes

2023-03-01 01:14 UTC, merged