#78: Added new PhpUnit extension and event subscriber to support PhpUnit v10 and deleted redundant PushDocumentation artisan command
RonasIT/laravel-swagger pull request #79
Opened 2023-03-04 14:08 UTC by vitgrams

…

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-07 07:46 UTC, vitgrams commented
@DenTray Implemented for phpUnit v 10. These changes will break backward compatibility.

2023-03-08 08:48 UTC, NikitaYakovlev approved these changes

2023-03-09 03:36 UTC, DenTray requested changes

2023-03-09 03:36 UTC, DenTray commented on src/Tests/PhpUnitEventSubscribers/SwaggerSubscriber.php
> +final class SwaggerSubscriber implements Event\Test\AfterLastTestMethodFinishedSubscriber
```suggestion
final class SwaggerSubscriber implements AfterLastTestMethodFinishedSubscriber
```

2023-03-09 03:36 UTC, DenTray commented on src/Tests/PhpUnitEventSubscribers/SwaggerSubscriber.php
> +final class SwaggerSubscriber implements Event\Test\AfterLastTestMethodFinishedSubscriber
```suggestion
final class SwaggerSaveDocumentationSubscriber implements Event\Test\AfterLastTestMethodFinishedSubscriber
```

2023-03-09 15:09 UTC, vitgrams commented
@DenTray Resolved review conversations.

2023-03-13 03:58 UTC, DenTray approved these changes

2023-03-13 03:59 UTC, DenTray commented
@vitgrams could you please cover new code by test cases

2023-03-14 15:55 UTC, vitgrams commented
@DenTray Increased code coverage by unit tests. I can't write test method for PhpUnit extension class because `notify()` method has mandatory event argument which is the object of the final class.

2023-03-15 08:10 UTC, vitgrams commented
@DenTray Please note that the changes from 78_save_temp_doc_in_file_for_local_and_storage_drivers branch have been merged into current branch because `rebase` operation is not allowed here.

2023-03-22 01:57 UTC, DenTray commented
@vitgrams could you please resolve conflicts

2023-06-20 03:42 UTC, DenTray commented
required new major version, waiting for stable master

2023-11-07 03:51 UTC, DenTray commented
@Goodmain could you please resolve conglicts

2023-11-07 18:52 UTC, Goodmain commented
@DenTray Done

2023-11-13 10:40 UTC, DenTray approved these changes

2023-11-13 10:42 UTC, merged