feat: removed unnecessary grouping by prefix
RonasIT/laravel-swagger pull request #92
Opened 2023-06-30 17:41 UTC by Adil9994

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #90  (issue)

## Type of change
Bug fix (non-breaking change which fixes an issue)

2023-07-06 07:27 UTC, DenTray requested changes

2023-07-06 07:27 UTC, DenTray commented on src/Services/SwaggerService.php
> +        $globalPrefix = config('auto-doc.global_prefix');
```suggestion
        $globalPrefix = Arr::get($this->config, 'global_prefix');
```

2023-07-06 07:27 UTC, DenTray commented on tests/fixtures/SwaggerServiceTest/tmp_data_global_post_user_request.json
> +	"swagger": "2.0",
please correct formatting

2023-07-06 07:27 UTC, DenTray commented on src/Services/SwaggerService.php
>          $explodedUri = explode('/', $this->uri);
```suggestion
        $explodedUri = explode('/', trim($this->uri, '/'));
```

2023-07-06 07:27 UTC, DenTray commented on src/Services/SwaggerService.php
> +            : Arr::get($explodedUri, 1);
please to implement something like this

```suggestion
        $tag = array_shift($explodedUri);

        if ($globalPrefix === $tag)) {
            $tag = array_shift($explodedUri);
        }
```

2023-07-06 07:27 UTC, DenTray commented on tests/SwaggerServiceTest.php
> +
please implement test case for global prefix equals `/global` and we call api `/global`

2024-03-10 04:53 UTC, Goodmain commented on Dockerfile
> +RUN if $(uname -m) == 'arm64';
Done

2024-03-10 04:53 UTC, Goodmain commented on src/Services/SwaggerService.php
> +        $globalPrefix = config('auto-doc.global_prefix');
Done

2024-03-10 04:54 UTC, Goodmain commented on src/Services/SwaggerService.php
>          $explodedUri = explode('/', $this->uri);
Done

2025-01-24 08:00 UTC, DenTray approved these changes

2025-01-24 08:01 UTC, merged